### ISSUE TITLE
entry LWRP should allow ability to set mode, owner, and group on known_hosts file

### ISSUE THREAD

**Issue by poliva83** [chef-cookbooks/ssh_known_hosts#26]
A file resource is being used inside this provider however there is no attributes in LWRP for mode, owner, and group to pass on to this file resource. I always end up having to call file resource again after entry LWRP block with :touch action just for purpose of setting mode, owner, and group.

**Comment by iennae** [comment]
@poliva83 Thanks so much for your request for this feature. We apologize for the delay in getting this created. It's now available with version 3.1.0 of this cookbook.

**Comment by poliva83** [comment]
Thanks @iennae for fixing this.
