### ISSUE TITLE
Link to bug system in CONTRIBUTING is wrong

### ISSUE THREAD

**Issue by Odaeus** [chef-cookbooks/ssh_known_hosts#39]
The link to http://tickets.chef.io does not work as the subdomain does not exist. Instead it seems like it should link to https://tickets.opscode.com/browse/CHEF.

**Comment by Odaeus** [comment]
Ha, strike that, it seems they have stopped using JIRA (yay), and are using GitHub now at https://github.com/chef/chef/issues. Does this mean I should file my actual issue on your issues list or the Chef one?!

**Comment by tas50** [comment]
The contributing docs have been completely replaced.  The old ones were totally wrong. Sorry about that.
