### ISSUE TITLE
Should convert DSA key name to DSS

### ISSUE THREAD

**Issue by Odaeus** [chef-cookbooks/ssh_known_hosts#40]
When writing the key line if the user has specified "dsa" as the `key_type` the script will write out "ssh-dsa" but I think it should be "ssh-dss" to work. "rsa" is correctly left untouched.

Relevant line: https://github.com/opscode-cookbooks/ssh_known_hosts/commit/4791dfb2a40372a89b8819ddb265aa7b17c8d5db#diff-335bb64cd132203fb779b6bb38fc1857R30

The SSH known_hosts format documentation doesn't appear to mention the "ssh-" field at all so I'm basing this off testing in my own environment.

**Comment by e100** [comment]
@Odaeus is correct, known_hosts file requires "ssh-dss" for dsa keys.  "ssh-dsa" does not work.

**Comment by iennae** [comment]
http://man.openbsd.org/ssh-keyscan.1 looks to have the following:
Output format for RSA, DSA, ECDSA, and Ed25519 keys:
host-or-namelist keytype base64-encoded-key
Where keytype is either “ecdsa-sha2-nistp256”, “ecdsa-sha2-nistp384”, “ecdsa-sha2-nistp521”, “ssh-ed25519”, “ssh-dss” or “ssh-rsa”.
/etc/ssh/ssh_known_hosts

so it looks like maybe the new ecdsa code we have added may be formatted incorrectly as well maybe? Thanks for filing this issue @Odaeus and @e100 for verifying! Will work on getting this fixed.
