### ISSUE TITLE
Using this cookbook on a machine without openssh-client fails

### ISSUE THREAD

**Issue by rbclark** [chef-cookbooks/ssh_known_hosts#41]
I have noticed that when using the provider in this cookbook on very lightweight machines (e.g. docker boxes) the recipe will error out with the error `No such file or directory - ssh-keyscan` due to https://github.com/opscode-cookbooks/ssh_known_hosts/blob/master/providers/entry.rb#L40. The simple fix for this on ubuntu at least is to install the openssh-client package, not sure about other distributions.

**Comment by iennae** [comment]
@rbclark Thanks for opening up this issue. We apologize for the delay in responding to this request. After some contemplation, I think that it works fine the way it is to minimize extra dependency for folks. Ideally this cookbook will become a library cookbook with just resources, and individuals have wrapper cookbooks that include exactly what they want with the specific configurations for any additional software. As ssh can be quite complex, I want to minimize the complexity of this cookbook. Please do reopen this issue with your further thoughts as necessary. Thanks again.
