### ISSUE TITLE
Newlines not being added between entries

### ISSUE THREAD

**Issue by westeras** [chef-cookbooks/ssh_known_hosts#44]
I am attempting to add 7 entries to the known hosts file.  The first 6 are concatenated onto a single line in the hosts file, with the last one being given its own line.  Obviously this prevents host verification from happening for all but the last host.  I checked out the v2.0.0 release commit and it works as it's supposed to, so the bug has been introduced somewhere between now and then.

**Comment by westeras** [comment]
This is with Chef 11 and on RHEL 6.7

**Comment by popsikle** [comment]
Ruby2 moved the $INPUT_RECORD_SEPERATOR variable to the std 'English' lib.  You can fix the resource by adding `alias $INPUT_RECORD_SEPERATOR $/ if $INPUT_RECORD_SEPERATOR.nil?` to line 46

**Comment by iennae** [comment]
@westeras can you verify that you are still seeing this behavior with the latest version of the cookbook? I think it's ok at this point.

Thanks!

**Comment by westeras** [comment]
Hi Jennifer, it's actually been a long while since I have used this cookbook or even chef in general (project change) but if I remember correctly I followed the advice of the other reply on this thread and that fixed the problem.

**Comment by iennae** [comment]
@westeras 
Thanks for the update! I appreciate your feedback. As I'm seeing a change in the output, (as we're using the English lib now) I'm going to go ahead and close this. If you find yourself using chef again, and running into this problem, please feel free to reopen. Thanks!
