### ISSUE TITLE
ssh-keyscan shell call causes chef-client worker to hang

### ISSUE THREAD

**Issue by kbruner** [chef-cookbooks/ssh_known_hosts#47]
We had a problem with chef-client workers hanging indefinitely, which I narrowed down to the ssh-keyscan run in a `ssh_known_hosts_entry 'github.com'` resource.  There seem to be cases where it will connect and never close/timeout, which means chef-client won't complete.  Any reason not to run ssh-keyscan with mixlib/shellout with its timeout?

**Comment by iennae** [comment]
@kbruner Thanks for this report. I've added shell_out with a timeout as of v 3.0.1 of the cookbook. Hopefully this resolves this issue for you. If not, please do reopen! Thanks!
