### ISSUE TITLE
Allow setting user, group, and mode of ssh_known_hosts file

### ISSUE THREAD

**Issue by haidangwa** [chef-cookbooks/ssh_known_hosts#49]
Using the LWRP, I need to be able to set the user, group, and mode for the ssh_known_hosts file, because I have a corporate security policy that needs to be enforced.

**Comment by jennyfountain** [comment]
+2 I need the same ability

**Comment by iennae** [comment]
@haidangwa Thanks so much for your request for this feature. We apologize for the delay in getting this updated. It's now available with the entry resource of version 3.1.0 of this cookbook. Please let us know if you have issues with the cookbook, and open a new issue if you discover problems.

**Comment by haidangwa** [comment]
Awesome, thank you!
