### ISSUE TITLE
Can't upgrade from 2.x to 4.x using only a local data bag.

### ISSUE THREAD

**Issue by aried3r** [chef-cookbooks/ssh_known_hosts#60]
### Cookbook version
4.0.0

### Chef-client version
12.13.37

### Platform Details
Ubuntu 14.04 LTS

### Scenario:
I'm upgrading from ssh_known_hosts 2.x to 4.x using only a local data bag using `knife solo`.

### Steps to Reproduce:
I have no config other than the data bag (see below) and `"recipe[ssh_known_hosts]"` in my `run_list`.
```JSON
{
  "id": "github",
  "fqdn": "github.com"
}
```

### Expected Result:
Running `knife solo cook` works.

### Actual Result:
I get an exception:
```
Recipe Compile Error in /home/admin/chef-solo/local-mode-cache/cache/cookbooks/ssh_known_hosts/recipes/default.rb
================================================================================

Net::HTTPFatalError
-------------------
500 "Internal Server Error"

Cookbook Trace:
---------------
  /home/admin/chef-solo/local-mode-cache/cache/cookbooks/ssh_known_hosts/libraries/helpers.rb:18:in `hosts_keys'
  /home/admin/chef-solo/local-mode-cache/cache/cookbooks/ssh_known_hosts/recipes/default.rb:36:in `from_file'
  /home/admin/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'
```

My guess is that since I neither use the `cacher`, nor have data bag on other nodes, [this line](https://github.com/chef-cookbooks/ssh_known_hosts/blob/3f2b2b0aa9384b2393a842ca00a1961d2dcab40e/recipes/default.rb#L36) gets executed and fails, never reaching the following lines that go through local data bags.

**Comment by lamont-granquist** [comment]
that is blowing up on search which smells like legacy mode chef-solo behavior.

there's not really enough information here to see where the error is.

for behavior this trivial, you should probably write your own recipe using the `ssh_known_hosts_entry` resource directly, and not use the default cookbook.

**Comment by aried3r** [comment]
Sorry for the late reply.

> there's not really enough information here to see where the error is.

What about my reference to the code? It seems that a simple `if/else` won't do in this case, because unless you set [`node['ssh_known_hosts']['use_data_bag_cache']`](https://github.com/chef-cookbooks/ssh_known_hosts/blob/3f2b2b0aa9384b2393a842ca00a1961d2dcab40e/recipes/default.rb#L24) a [search](https://github.com/chef-cookbooks/ssh_known_hosts/blob/3f2b2b0aa9384b2393a842ca00a1961d2dcab40e/recipes/default.rb#L36) will always be executed.

> for behavior this trivial, you should probably write your own recipe using the ssh_known_hosts_entry resource directly, and not use the default cookbook.

I agree, but still, isn't this a bug in the code? Since the README states a simple data bag works, _explicitly_ covering this trivial use case?
