### ISSUE TITLE
Error executing action `create` on resource 'ssh_known_hosts_entry[github.com]'

### ISSUE THREAD

**Issue by guillefar** [chef-cookbooks/ssh_known_hosts#69]
So, I'm receiving this error running the recipe: 
# 
# Error executing action `create` on resource 'ssh_known_hosts_entry[github.com]'
## NoMethodError

undefined method `resource_collection' for nil:NilClass

For the record, I added the cookbook metadata.rb :
`depends 'ssh_known_hosts'`

and in the recipe I use it as: 
`ssh_known_hosts_entry 'github.com'`

I'm using AWS opsworks chef which is version 12. 

SO: Ubuntu 16.04

Any idea what could be causing this?

**Comment by tas50** [comment]
We've refactored the provider in this cookbook. Give it a try now

**Comment by dankozlowski** [comment]
I'm getting a similar error at this step, although with a different message:

```
  No resource or method named `type_string' for `LWRP resource ssh_known_hosts_entry from cookbook ssh_known_hosts action provider "github.com"'
```

Any idea what could be causing this?
