### ISSUE TITLE
Host key verification failed after upgrading from 4.0.0 to 4.1.0

### ISSUE THREAD

**Issue by fletchowns** [chef-cookbooks/ssh_known_hosts#72]
### Cookbook version
4.1.0

### Chef-client version
12.10.24

### Platform Details
Red Hat Enterprise Linux Server release 7.2 (Maipo) on AWS, based on ami-d1315fb1

### Scenario:
I had the following in my recipe:
```ruby
ssh_known_hosts_entry "bitbucket.org,131.103.20.167" do
	key 'AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=='
end

ssh_known_hosts_entry "bitbucket.org,131.103.20.168" do
	key 'AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=='
end
```

After upgrading to latest 4.1.0 version of this cookbook, it changed my `/etc/ssh/ssh_known_hosts` as follows during converge:
```
mybox.myorg.com   * template[update ssh known hosts file] action create
mybox.myorg.com     - update content in file /etc/ssh/ssh_known_hosts from 353c0a to 4a1b31
mybox.myorg.com     --- /etc/ssh/ssh_known_hosts	2016-11-03 23:46:42.832187975 +0000
mybox.myorg.com     +++ /etc/ssh/.chef-update ssh known hosts file20170105-24339-gw9cdy	2017-01-05 19:35:53.624325221 +0000
mybox.myorg.com     @@ -1,3 +1,3 @@
mybox.myorg.com     -bitbucket.org,131.103.20.167 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
mybox.myorg.com     -bitbucket.org,131.103.20.168 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
mybox.myorg.com     +[bitbucket.org,131.103.20.167]:22 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
mybox.myorg.com     +[bitbucket.org,131.103.20.168]:22 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
```

Later on the converge fails on the git resource, it doesn't seem to like the []:22 in the entries:
```
mybox.myorg.com STDERR: Host key verification failed.
mybox.myorg.com fatal: Could not read from remote repository.
```

If I roll back to 4.0.0 version of this cookbook, it works fine. Only difference seems to be no more []:22 in the entries. (Yes I also realized my bitbucket ips are out of date!)

**Comment by jeffbyrnes** [comment]
I have a related, but different, issue: the changes in a160f79440c5f6d6c927e8b6a72a7e2ca5fddedf result in a `git` resource no longer working on first convergence, as the `known_hosts` aren’t written until the end of the run.

Happy to file that as a separate issue, if preferred.

**Comment by fletchowns** [comment]
Did this one get fixed? I just tried with 5.0.0 and it doesn't seem to be putting []:22 in there anymore

**Comment by lamont-granquist** [comment]
according to the changelog :22 fixed that.

and @jeffbyrnes that is intended behavior.  you should probably switch to writing ~/.ssh/known_hosts to the homedir of the user issuing the git resource and not rely on the global ssh known hosts file.

**Comment by jeffbyrnes** [comment]
@lamont-granquist thanks for clarifying. Just frustrating that that _wasn’t_ the behavior until recently. One of those trick “bug as a feature” things, and I was enjoying the feature.

I’ll see about refactoring my cookbooks to write to the specific user’s `known_hosts`.

**Comment by lamont-granquist** [comment]
yeah, the way it worked was terrible.

sorry about the way it got released, i was working on master and then got pulled off onto other things and tim shipped it without bumping the major and without a release announcement, but at this point that train left the station awhile ago.

**Comment by jeffbyrnes** [comment]
@lamont-granquist haha, yeah, I get it. So it goes; thanks for the hard word regardless!

**Comment by daften** [comment]
@jeffbyrnes which cookbook / resource do you use for the user specific known_hosts?
ALso, can somebody explain why the global ssh_known_hosts file is so terrible? For a build server, it's easer to have several tools have access to the central git repo's than have each user define it individually.

Thanks! :)

**Comment by jeffbyrnes** [comment]
@daften my solution, kludge-y though it may be, has been to pin to the older version of this cookbook 😃 

I really do wish there was a way to update the known_hosts immediately, instead of delayed, but it works, so I’m good.

I’ve not found a cookbook to manage `known_hosts` on a per-user basis.

**Comment by daften** [comment]
Thanks @jeffbyrnes ;)
