### ISSUE TITLE
Entry Resource not appending

### ISSUE THREAD

**Issue by josh-barker** [chef-cookbooks/ssh_known_hosts#74]
### Cookbook version
4.1.1

### Chef-client version
12.15.19

### Platform Details
Redhat 7.3

### Scenario:
When using the custom resource, I'm expecting it to **append** to the known hosts file. However, it is replacing the entire file with 1 entry.
 
### Steps to Reproduce:
In attributes/default.rb
```
default['ssh_known_hosts']['file'] = '/home/user/.ssh/known_hosts'
```

In a recipe, I have the following:

```
ssh_known_hosts_entry 'my.awesome.host.com' do
  owner 'user'
  group 'group'
  action :create
end
```
### Expected Result:
Existing known hosts should remain and 1 extra entry should be added.

### Actual Result:
The known hosts file only has:
```
my.awesome.host.com ssh-rsa ..................

```

**Comment by signe** [comment]
I am seeing this same issue.  It appears that the resource can't find existing keys correctly, and it's purging any existing keys.

I believe this was broken in ebe9abf9d0a65587480e9997d3f455e935f20245 for the 4.1 release, becaose 4.0 is working fine.

**Comment by lamont-granquist** [comment]
That is intended behavior.

The change in 4.1 should have a been a major version break (that should have been 5.0, and 5.0 should have been 6.0)

The chef-client run now needs to collect all of the information in order to fully manage the entire file.

Something like this may replicate the old behavior:

```ruby
 lines = ::File.readlines(node['ssh_known_hosts']['file'])
 hosts = lines.map(&:chmop).reject(&:empty).map do |line|
   fields = line.split(/\s+/)
   {
     "fqdn" => fields[0],
     "key_type" => fields[1],
     "key" => fields[2]
   }
 end
 ssh_known_hosts_entries hosts
```

**Comment by signe** [comment]
How is completely breaking a system's known_hosts file intended behavior?  That is _seriously_ messed up.

**Comment by signe** [comment]
And how is it not documented anywhere?  The documentation specifically says "adding hosts", not "definitively managing the entire known_hosts file".

**Comment by signe** [comment]
![image](https://cloud.githubusercontent.com/assets/249456/23715646/246c2058-03e2-11e7-9c4c-b093643bd846.png)
