### ISSUE TITLE
Using recently added ssh host does not work until next provision/converge

### ISSUE THREAD

**Issue by starx** [chef-cookbooks/ssh_known_hosts#77]
### Cookbook version
4 or higher

### Scenario:
I am trying to add a host of for the repository like `github.com` and then pull down the repository using a bash script. I am not using the git resource because the key I am using is passphrase protected. 

### Steps to Reproduce:
Create a simple cookbook with the following code in the default cookbook

```
ssh_known_hosts_entry 'github.com'
bash "Setting up repository" do
  user 'root'
  code <<-EOH
  		mkdir /var/www
  		cd /var/www
		git init
		git remote add origin git@github.com:starx/DockerCentOS6.3LAMP.git
		git pull --depth=1 origin master  
  EOH
end
```

For the sake of seeing the issue, we don't actually need to add the ssh-key. 

Or, download [this](https://files.slack.com/files-pri/T0M1PBN4E-F4XGZ7EDR/download/test_cookbook.tar.gz) and test using kitchen.

### Expected Result:
Host to be recognized on the first run and allowed to proceed by getting the error of `Could not read from remote repository.` because an ssh key has not been added yet.

### Actual Result:

Fails by saying `Host key verification failed.` 
Sample full log of `kitchen converge` https://pastebin.com/TUBg3ASA

**Comment by cheeseplus** [comment]
The cookbook changed in 4.1 which fundamentally altered when the changes become available to the run which causes the behaviour above. We're investigating the best fix going forward.

**Comment by mikelococo** [comment]
Seems like this is already triaged, but I confirm this as well.

**Comment by jslusher** [comment]
This is a nasty one for us since we're trying to use Packer to build AMIs. In that scenario a second chef converge isn't an option. Is the workaround just to use an earlier version of the cookbook?

**Comment by PierreBeucher** [comment]
Same issue here. It seems a `:delayed` is added on the template used to create ssh_known_hosts (see [entry.rb:64](https://github.com/chef-cookbooks/ssh_known_hosts/blob/72c7f104640e4633bfba3234a002eb22c006f3fd/resources/entry.rb#L64))

This is shown in the log given by @starx (I have similar logs)

         * ssh_known_hosts_entry[github.com] action create (up to date)
         * log[force delayed notification] action write
         * template[update ssh known hosts file] action nothing (skipped due to action :nothing)

And at the very end, after the script failed:

          template[update` ssh known hosts file] action create
           - create new file /etc/ssh/ssh_known_hosts
           - update content in file /etc/ssh/ssh_known_hosts from none to 51b2be

@lamont-granquist mentioned in a comment for this `:delayed` feature:
> XXX: remove log resource once delayed_actions lands in compat_resource

As compat_resource seems unused since 5.0.0 (cf. changelog) I assume we can safely remove this delayed property. I'll try and make a pull request.

**Comment by adamcrown** [comment]
Any updates on this? This is a real deal breaker for me.

**Comment by sekrett** [comment]
I reverted to version 4.0 and it works fine. Don't see any reason to upgrade. Any useful feature added?

**Comment by aspyatkin** [comment]
It's been three months already. When does the problem get fixed?

**Comment by fletchowns** [comment]
Is there any workaround other than reverting to 4.0?

**Comment by tas50** [comment]
At the moment if you need immediate known hosts functionality I'd recommend the older ssh know hosts cookbook. As for the fix it's going to require reworking a lot of things in this cookbook. It needs to get done and it's on the whiteboard in my office to do, but there's a big backlog.

**Comment by fletchowns** [comment]
Right on, thanks @tas50 . And thank you for everything that you do Tim, you make a lot of peoples lives easier!

**Comment by easydevmixin** [comment]
Agreed this is a big stopper. Thanks @sekrett and @tas50 for the suggestion. This solved my issue.

**Comment by rabidscorpio** [comment]
@tas50 Is there an update on this? Can we get #82 merged so that people can use the current version? There's really not much that needs to be done to get it usable. Cheers!
