### ISSUE TITLE
Copyright question

### ISSUE THREAD

**Issue by damm** [chef-cookbooks/ssh_known_hosts#78]
1. https://github.com/chef-cookbooks/ssh_known_hosts/blob/master/recipes/default.rb#L9
  Does this really need to still extend to 2017? That company no longer exists I stopped working for them in 2010 so shouldn't it end there? 

They don't publish the cookbook anywhere in their name; other than the original source I linked there really shouldn't be any need to include them in the copyright possibly.

**Comment by tas50** [comment]
The copyright was added at some point in this cookbook's history and that doesn't require the company to actually release the cookbook. That's all legit per Apache 2.0 license. Does it need to be extended? Not really. Is it hurting anything? Not really. I think we should just keep it as a historical copyright. Whether the company dissolved or was acquired someone still owns the company's work including this bit of code.

**Comment by damm** [comment]
Well I was the only person who released it; I just copyrighted them.  I was just trying to make sure as it felt weird to see it extended to 2017.

Thanks
